# -*- coding: utf-8 -*-
"""Code of assingment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MkGpbyHwacGMKuNZJ8KuRXb8RiLsrxIn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score



df=pd.read_excel('data_transform1.xlsx')
df.head()

X=df.iloc[:,0].values
y=df.iloc[:,1].values
X,y

plt.scatter(X,y)



regressor=LinearRegression()
regressor.fit(X.reshape(-1,1),y)

print(regressor.coef_)
print(regressor.intercept_)

y_pred=regressor.predict(X.reshape(-1,1))
y_pred
r2_score(y,y_pred)

y_new=np.log(y)
y_new

regressor1=LinearRegression()
regressor1.fit(X.reshape(-1,1),y_new)

print(regressor1.coef_)
print(regressor1.intercept_)

y_pred1=regressor1.predict(X.reshape(-1,1))
y_pred1
r2_score(y_new,y_pred1)

